-- MySQL Script generated by MySQL Workbench
-- Mon Jun  6 20:30:44 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema forum
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `forum` ;

-- -----------------------------------------------------
-- Schema forum
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `forum` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `forum` ;

-- -----------------------------------------------------
-- Table `forum`.`forum`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `forum`.`forum` ;

CREATE TABLE IF NOT EXISTS `forum`.`forum` (
                                               `id` BIGINT NOT NULL,
                                               `title` TEXT NULL DEFAULT NULL,
                                               PRIMARY KEY (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `forum`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `forum`.`user` ;

CREATE TABLE IF NOT EXISTS `forum`.`user` (
                                              `id` BIGINT NOT NULL,
                                              `userName` VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NULL DEFAULT NULL,
    `joinDate` DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `forum`.`topic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `forum`.`topic` ;

CREATE TABLE IF NOT EXISTS `forum`.`topic` (
                                               `id` BIGINT NOT NULL,
                                               `title` TEXT NULL DEFAULT NULL,
                                               `createdTime` DATETIME NULL DEFAULT NULL,
                                               `content` TEXT NULL DEFAULT NULL,
                                               `forum_id` BIGINT NOT NULL,
                                               `user_id` BIGINT NOT NULL,
                                               PRIMARY KEY (`id`, `forum_id`),
    INDEX `fk_topic_forum1_idx` (`forum_id` ASC) VISIBLE,
    INDEX `fk_topic_user1_idx` (`user_id` ASC) VISIBLE,
    CONSTRAINT `fk_topic_forum1`
    FOREIGN KEY (`forum_id`)
    REFERENCES `forum`.`forum` (`id`),
    CONSTRAINT `fk_topic_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `forum`.`user` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `forum`.`replymessage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `forum`.`replymessage` ;

CREATE TABLE IF NOT EXISTS `forum`.`replymessage` (
                                                      `id` BIGINT NOT NULL,
                                                      `title` TEXT NULL DEFAULT NULL,
                                                      `createdTime` DATETIME NULL DEFAULT NULL,
                                                      `content` TEXT NULL DEFAULT NULL,
                                                      `topic_id` BIGINT NOT NULL,
                                                      PRIMARY KEY (`id`),
    INDEX `fk_replymessage_topic_idx` (`topic_id` ASC) VISIBLE,
    CONSTRAINT `fk_replymessage_topic`
    FOREIGN KEY (`topic_id`)
    REFERENCES `forum`.`topic` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



INSERT INTO `forum`.`user` (`id`, `user_name`, `password`, `join_date`) VALUES ('1', 'tuyen326', '123456', '2021-11-21');
INSERT INTO `forum`.`user` (`id`, `user_name`, `password`, `join_date`) VALUES ('2', 'tuyen123', '123456', '2021-11-19');

INSERT INTO `forum`.`forum` (`id`, `title`) VALUES ('1', 'haha');
INSERT INTO `forum`.`forum` (`id`, `title`) VALUES ('2', 'hihi');
INSERT INTO `forum`.`forum` (`id`, `title`) VALUES ('2', 'kakaka');

INSERT INTO `forum`.`forum` (`id`, `title`) VALUES ('1', 'haha');
INSERT INTO `forum`.`forum` (`id`, `title`) VALUES ('2', 'hihi');
INSERT INTO `forum`.`forum` (`id`, `title`) VALUES ('3', 'kakaka');

INSERT INTO `forum`.`topic` (`id`, `title`, `created_time`, `content`, `forum_id`, `user_id`) VALUES ('1', 'Học phí', '2022-06-05', 'Học phí cao quá đóng không nổi nên đành nghỉ học', '1', '1');

INSERT INTO `forum`.`replymessage` (`id`, `title`, `created_time`, `content`, `topic_id`) VALUES ('1', 'jiiihihh', '2022-06-01', 'huhuh', '1');
